import '../models/besin.dart';

class BesinVerileri {
  static List<Besin> getOrnekBesinler() {
// Bu dosya sabit besin verilerini veya yardımcı fonksiyonları içerir.
    return [
      // Kahvaltılık
      Besin(
        id: 1,
        isim: "Haşlanmış Yumurta",
        kalori: 72,
        protein: 6.3,
        karbonhidrat: 0.6,
        yag: 5.0,
        fiber: 0.0,
        kategori: "Kahvaltılık",
      ),
      Besin(
        id: 2,
        isim: "Beyaz Peynir",
        kalori: 85,
        protein: 6.0,
        karbonhidrat: 1.0,
        yag: 6.0,
        fiber: 0.0,
        kategori: "Kahvaltılık",
      ),
      Besin(
        id: 3,
        isim: "Bal",
        kalori: 64,
        protein: 0.1,
        karbonhidrat: 17.0,
        yag: 0.0,
        fiber: 0.0,
        kategori: "Kahvaltılık",
      ),
      Besin(
        id: 4,
        isim: "Zeytin",
        kalori: 115,
        protein: 0.8,
        karbonhidrat: 6.0,
        yag: 11.0,
        fiber: 3.0,
        kategori: "Kahvaltılık",
      ),
      Besin(
        id: 5,
        isim: "Domates",
        kalori: 18,
        protein: 0.9,
        karbonhidrat: 3.9,
        yag: 0.2,
        fiber: 1.2,
        kategori: "Kahvaltılık",
      ),
      Besin(
        id: 31,
        isim: "Kaşar Peyniri",
        kalori: 95,
        protein: 7.0,
        karbonhidrat: 1.0,
        yag: 7.5,
        fiber: 0.0,
        kategori: "Kahvaltılık",
      ),
      Besin(
        id: 32,
        isim: "Siyah Zeytin",
        kalori: 115,
        protein: 0.8,
        karbonhidrat: 6.0,
        yag: 11.0,
        fiber: 3.0,
        kategori: "Kahvaltılık",
      ),
      Besin(
        id: 33,
        isim: "Salatalık",
        kalori: 16,
        protein: 0.7,
        karbonhidrat: 3.6,
        yag: 0.1,
        fiber: 0.5,
        kategori: "Kahvaltılık",
      ),
      Besin(
        id: 34,
        isim: "Simit",
        kalori: 250,
        protein: 7.0,
        karbonhidrat: 50.0,
        yag: 4.2,
        fiber: 2.0,
        kategori: "Kahvaltılık",
      ),
      Besin(
        id: 35,
        isim: "Reçel",
        kalori: 56,
        protein: 0.1,
        karbonhidrat: 14.0,
        yag: 0.0,
        fiber: 0.1,
        kategori: "Kahvaltılık",
      ),
      Besin(
        id: 36,
        isim: "Tereyağı",
        kalori: 102,
        protein: 0.1,
        karbonhidrat: 0.0,
        yag: 11.5,
        fiber: 0.0,
        kategori: "Kahvaltılık",
      ),
      Besin(
        id: 37,
        isim: "Menemen",
        kalori: 150,
        protein: 6.0,
        karbonhidrat: 7.0,
        yag: 11.0,
        fiber: 1.5,
        kategori: "Kahvaltılık",
      ),

      // Ana Yemek
      Besin(
        id: 6,
        isim: "Tavuk Göğsü",
        kalori: 165,
        protein: 31.0,
        karbonhidrat: 0.0,
        yag: 3.6,
        fiber: 0.0,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 7,
        isim: "Pirinç",
        kalori: 130,
        protein: 2.7,
        karbonhidrat: 28.0,
        yag: 0.3,
        fiber: 0.4,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 8,
        isim: "Mercimek Çorbası",
        kalori: 116,
        protein: 9.0,
        karbonhidrat: 20.0,
        yag: 0.4,
        fiber: 7.9,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 9,
        isim: "Köfte",
        kalori: 250,
        protein: 18.0,
        karbonhidrat: 8.0,
        yag: 15.0,
        fiber: 1.0,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 10,
        isim: "Makarna",
        kalori: 131,
        protein: 5.0,
        karbonhidrat: 25.0,
        yag: 1.1,
        fiber: 2.5,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 38,
        isim: "Etli Güveç",
        kalori: 220,
        protein: 18.0,
        karbonhidrat: 8.0,
        yag: 13.0,
        fiber: 2.0,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 39,
        isim: "Biber Dolması",
        kalori: 180,
        protein: 5.0,
        karbonhidrat: 25.0,
        yag: 7.0,
        fiber: 3.0,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 40,
        isim: "Kuru Fasulye",
        kalori: 140,
        protein: 8.0,
        karbonhidrat: 22.0,
        yag: 3.0,
        fiber: 7.0,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 41,
        isim: "Pilav (Bulgur)",
        kalori: 120,
        protein: 3.0,
        karbonhidrat: 25.0,
        yag: 1.0,
        fiber: 2.0,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 42,
        isim: "Izgara Balık",
        kalori: 180,
        protein: 20.0,
        karbonhidrat: 0.0,
        yag: 10.0,
        fiber: 0.0,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 43,
        isim: "Fırında Tavuk But",
        kalori: 210,
        protein: 18.0,
        karbonhidrat: 2.0,
        yag: 14.0,
        fiber: 0.0,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 44,
        isim: "Zeytinyağlı Taze Fasulye",
        kalori: 90,
        protein: 2.0,
        karbonhidrat: 12.0,
        yag: 4.0,
        fiber: 4.0,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 45,
        isim: "Sebzeli Bulgur Pilavı",
        kalori: 130,
        protein: 3.5,
        karbonhidrat: 27.0,
        yag: 1.2,
        fiber: 2.5,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 46,
        isim: "Tavuk Sote",
        kalori: 160,
        protein: 17.0,
        karbonhidrat: 4.0,
        yag: 8.0,
        fiber: 1.0,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 47,
        isim: "Sebze Çorbası",
        kalori: 70,
        protein: 2.0,
        karbonhidrat: 10.0,
        yag: 2.0,
        fiber: 2.0,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 48,
        isim: "Yoğurt",
        kalori: 60,
        protein: 3.5,
        karbonhidrat: 4.0,
        yag: 3.0,
        fiber: 0.0,
        kategori: "Ana Yemek",
      ),
      Besin(
        id: 49,
        isim: "Et",
        kalori: 250,
        protein: 26.0,
        karbonhidrat: 0.0,
        yag: 18.0,
        fiber: 0.0,
        kategori: "Ana Yemek",
      ),

      // Meyve
      Besin(
        id: 11,
        isim: "Muz",
        kalori: 88,
        protein: 1.1,
        karbonhidrat: 23.0,
        yag: 0.3,
        fiber: 2.6,
        kategori: "Meyve",
      ),
      Besin(
        id: 12,
        isim: "Elma",
        kalori: 52,
        protein: 0.3,
        karbonhidrat: 14.0,
        yag: 0.2,
        fiber: 2.4,
        kategori: "Meyve",
      ),
      Besin(
        id: 13,
        isim: "Portakal",
        kalori: 47,
        protein: 0.9,
        karbonhidrat: 12.0,
        yag: 0.1,
        fiber: 2.4,
        kategori: "Meyve",
      ),
      Besin(
        id: 14,
        isim: "Çilek",
        kalori: 32,
        protein: 0.7,
        karbonhidrat: 8.0,
        yag: 0.3,
        fiber: 2.0,
        kategori: "Meyve",
      ),
      Besin(
        id: 15,
        isim: "Kivi",
        kalori: 61,
        protein: 1.1,
        karbonhidrat: 15.0,
        yag: 0.5,
        fiber: 3.0,
        kategori: "Meyve",
      ),

      // Sebze
      Besin(
        id: 16,
        isim: "Brokoli",
        kalori: 34,
        protein: 2.8,
        karbonhidrat: 7.0,
        yag: 0.4,
        fiber: 2.6,
        kategori: "Sebze",
      ),
      Besin(
        id: 17,
        isim: "Havuç",
        kalori: 41,
        protein: 0.9,
        karbonhidrat: 10.0,
        yag: 0.2,
        fiber: 2.8,
        kategori: "Sebze",
      ),
      Besin(
        id: 18,
        isim: "Ispanak",
        kalori: 23,
        protein: 2.9,
        karbonhidrat: 3.6,
        yag: 0.4,
        fiber: 2.2,
        kategori: "Sebze",
      ),
      Besin(
        id: 19,
        isim: "Salatalık",
        kalori: 16,
        protein: 0.7,
        karbonhidrat: 3.6,
        yag: 0.1,
        fiber: 0.5,
        kategori: "Sebze",
      ),
      Besin(
        id: 20,
        isim: "Patates",
        kalori: 77,
        protein: 2.0,
        karbonhidrat: 17.0,
        yag: 0.1,
        fiber: 2.2,
        kategori: "Sebze",
      ),

      // Atıştırmalık
      Besin(
        id: 21,
        isim: "Badem",
        kalori: 164,
        protein: 6.0,
        karbonhidrat: 6.0,
        yag: 14.0,
        fiber: 3.5,
        kategori: "Atıştırmalık",
      ),
      Besin(
        id: 22,
        isim: "Ceviz",
        kalori: 185,
        protein: 4.3,
        karbonhidrat: 4.0,
        yag: 18.0,
        fiber: 1.9,
        kategori: "Atıştırmalık",
      ),
      Besin(
        id: 23,
        isim: "Çikolata",
        kalori: 208,
        protein: 2.0,
        karbonhidrat: 25.0,
        yag: 12.0,
        fiber: 2.0,
        kategori: "Atıştırmalık",
      ),
      Besin(
        id: 24,
        isim: "Cips",
        kalori: 536,
        protein: 7.0,
        karbonhidrat: 53.0,
        yag: 35.0,
        fiber: 4.0,
        kategori: "Atıştırmalık",
      ),
      Besin(
        id: 25,
        isim: "Kraker",
        kalori: 502,
        protein: 10.0,
        karbonhidrat: 63.0,
        yag: 26.0,
        fiber: 2.0,
        kategori: "Atıştırmalık",
      ),

      // İçecek
      Besin(
        id: 26,
        isim: "Süt",
        kalori: 42,
        protein: 3.4,
        karbonhidrat: 5.0,
        yag: 1.0,
        fiber: 0.0,
        kategori: "İçecek",
      ),
      Besin(
        id: 27,
        isim: "Portakal Suyu",
        kalori: 45,
        protein: 0.7,
        karbonhidrat: 10.0,
        yag: 0.2,
        fiber: 0.2,
        kategori: "İçecek",
      ),
      Besin(
        id: 28,
        isim: "Yeşil Çay",
        kalori: 1,
        protein: 0.0,
        karbonhidrat: 0.0,
        yag: 0.0,
        fiber: 0.0,
        kategori: "İçecek",
      ),
      Besin(
        id: 29,
        isim: "Kahve",
        kalori: 2,
        protein: 0.3,
        karbonhidrat: 0.0,
        yag: 0.0,
        fiber: 0.0,
        kategori: "İçecek",
      ),
      Besin(
        id: 30,
        isim: "Su",
        kalori: 0,
        protein: 0.0,
        karbonhidrat: 0.0,
        yag: 0.0,
        fiber: 0.0,
        kategori: "İçecek",
      ),
    ];
  }
}
